name: fusion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  image_picker: ^1.0.7
  provider: ^6.1.1
  permission_handler: ^11.3.0
  app_settings: ^5.1.1
  firebase_storage: ^11.6.6
  animated_bottom_navigation_bar: ^1.3.2
  flutter_screenutil: ^5.9.0
  velocity_x: ^4.1.2
  pinput: ^3.0.1
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  flutter_slidable:
    path: custom_package/flutter_slidable
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"

  image_path: "assets/firebase_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/firebase_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
    - assets/font/
    - assets/
    - assets/icons/clock 1.png
  fonts:
    - family: Yellowtail Regular
      fonts:
        - asset: assets/font/Yellowtail-Regular.ttf
    - family: Lato Regular
      fonts:
        - asset: assets/font/Lato-Regular.ttf



